name: daviscru
version: 0.0.1
dependencies:
  redstone: ">= 0.5.18"
  redstone_mapper_mongo: any
  grinder: any
  shelf_static: any
  dart_config: any
  http: any
  crypto: any

  google_oauth2_client: ">= 0.4.1"
  google_plus_v1_api: any
  browser: any
  angular: ">= 1.0.0"
  route_hierarchical: any
  path: any
dependency_overrides:
  route_hierarchical:
    git:
      url: git://github.com/dgresham/route.dart.git
      ref: route-with-slashes
transformers:
- angular